config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  root 'static_pages#home'
  get "/import", to: 'static_pages#import'
  resources :card_files
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card_file.rb
class CardFile < ApplicationRecord
  belongs_to :user
  has_many :words
  validates :filename, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :card_files

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  def self.from_omniauth(auth)
    where(provider: auth["provider"], uid: auth["uid"]).first_or_create do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["nickname"]
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :card_file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/card_files_controller.rb
class CardFilesController < ApplicationController
  def index
  end

  def show
    if user_signed_in?
      user_id=current_user.id
      @card_files=current_user.card_files
      if @card_files.present?
        card_name = params[:card_name]
          if !card_name.present?
            card_name=@card_files[0].name
          end
        id=Cardfile.find_by_sql(['select id from userfiles where user_id=:userid and filename=:filename',{userid: userId,filename: fileName}])
        gon.cards=Word.find_by_sql(['select id,English,Japanese,Weak from words where fileid=:id',{id: id}])
        render json: { :homearr => gon.cards } and return if request.xhr?
      end
    end
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))
    if @user.persisted?
      flash.notice = "Login successful!"
      sign_in  @user
      redirect_to root_url
    else
      session["devise.user_attributes"] = @user.attributes
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      if current_user.card_files.present?
        @card = current_user.card_files.first
      end
    end
  end

  def import
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_files_helper.rb
module CardFilesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/card_files/edit.html.erb
<h1>CardFiles#edit</h1>
<p>Find me in app/views/card_files/edit.html.erb</p>

app/views/card_files/index.html.erb
<h3 class="edit_title">Edit</h3>
<div>
  <div class="editing_field">
    <% if @userfiles.present? %>
    <ul class="file_list demo-list-item mdl-list">
      <% i=1 %>
      <% for userfile in @userfiles %>
          <% if !(i%2==1) then %>
            <li class="list_color">
          <% else %>
            <li class="list_non_color">
          <% end %>
              <span class="mdl-list__item-primary-content">
                  <%= userfile.filename %>
                  <button class='editing_button mdl-js-button  mdl-button--colored' onclick="deleteCards('<%=userfile.id%>')">delete</button>
                  <%= link_to "edit", editing_edit_url(:fileId => userfile.id), class: 'editing_button_edit editing_button mdl-js-button  mdl-button--colored', method: :get %>
                  <button class='editing_button editing_button_download mdl-js-button  mdl-button--colored' onclick="DbToJson('<%=userfile.id%>')">download</button>
              </span>
            </li>
          <% i+=1 %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
<%= link_to 'Back', root_path,class:'back_button mdl-button mdl-js-button mdl-button--primary' %>

app/views/card_files/new.html.erb
<div class="form">以下に英語とそれの日本語訳を記入し自分のフラッシュカードを作成できます<br>
  <% if user_signed_in? #userが存在するかの確認 %>
      <div class="json_to_db">
        <label for="file" class="file">
          <input type="file" name="file" value="" id="file">
          <div id="JsonToDb" class="mdl-button mdl-js-button mdl-button--accent">ファイルをDBに保存</div>
        </label>
        <input type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect" onClick=importJson() value=決定></input><br><br>
      </div><br>
  <% end %>
  <div class="mdl-textfield mdl-js-textfield export_file_name">
    <input class="mdl-textfield__input" type="text" id="title">
    <!-- <label class="title mdl-textfield__label" for="title">保存するタイトル名</label> -->
  </div>
  <br>
  <div class="mdl-textfield mdl-js-textfield">
    <textarea class="mdl-textfield__input lined" type="text" rows="25" id="english"></textarea>
    <label class="mdl-textfield__label" for="english">　　　　please write English here...</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield">
    <textarea class="mdl-textfield__input lined" type="text" rows="25" id="japanese"></textarea>
    <label class="mdl-textfield__label" for="japanese">　　　　please write Japanese here...</label>
  </div></br>
  <% if !user_signed_in? #userが存在するかの確認 %>
    <input type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect" onClick=createJson() value=ダウンロードリンクの生成>
  <% else %>
    <input type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect" onClick=CardsToDb() value=保存 remote:true>

    <label for="file" class="file">
      <input type="file" name="file" value="" id="file">
    </label>
  <% end %>
  <div class="error_msg">
  </div>
</br>
</div>

<%= link_to 'Back', root_path,class:'back_button mdl-button mdl-js-button mdl-button--primary' %>

app/views/card_files/show.html.erb
<div class="mdl-layout__drawer">
  <span class="mdl-layout-title">ChooseCards</span>
  <nav class="mdl-navigation">
  <% if @card_files.present? %>
    <% for card_file in @card_files %>
      <a class="mdl-navigation__link" href="#" onClick="findCards('<%= card_file.name %>')">
        <%= card_file.name %>
      </a>
    <% end %>
  <% end %>
  <div id="import_file">
  </div>
  </nav>
</div>
<main class="mdl-layout__content">
  <div class="page-content"></div>
  <!-- スナックバー用コンテナ-->
  <div id="demo-toast-example" class="mdl-js-snackbar mdl-snackbar">
    <div class="mdl-snackbar__text"></div>
    <button class="mdl-snackbar__action" type="button"></button>
  </div>
</main>
<%= link_to 'Back', root_path,class:'back_button mdl-button mdl-js-button mdl-button--primary' %>

app/views/layouts/_header.html.erb
<header class="mdl-layout__header">
  <div class="mdl-layout__header-row">
    <span class="mdl-layout-title" id="big_title">
      <%= link_to 'EPC',root_path,class:"header_title" %>
    </span>
    <input id="vocalization" class="vocalization" type="text" placeholder="入力した単語を再生"></form>
    <button class="vocalization_button mdl-js-button  mdl-button--colored">
      <i class="material-icons  ">play_arrow</i>
    </button>
    <!-- userが存在するかの確認 -->
    <div class="user_info">
      <% if user_signed_in?  %>
        <span class="current_user"><%= current_user.username %>さん</span>
        <%= link_to 'LogOut', destroy_user_session_path, :method => 'delete',class:"mdl-button mdl-js-button mdl-button--raised login_button" %>
      <% else %>
        <%= link_to 'Login',new_user_session_path,class:"mdl-button mdl-js-button mdl-button--raised login_button" %>
      <% end %>
    </div>
  </div>

  <!-- <nav>
    <% if user_signed_in? %>
      <%= link_to 'ProfileEdit', edit_user_registration_path %>
      <%= current_user.username %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Signup', new_user_registration_path %>
      <%= link_to 'Login', new_user_session_path %>
    <% end %>
  </nav> -->

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EPCR</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="top-all">
  <div class="demo-card-wide mdl-card mdl-shadow--2dp top-mdl-card">
    <div class="mdl-card__title flash_card_top"></div>
    <div class="mdl-card__supporting-text top-comment">
      自分のフラッシュカードで学習できます<br>
      発音の採点機能・再生機能があります
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <% if current_user.card_files.present? %>
        <%= link_to 'FlashCard',card_file_path(@card),class:"top_button mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
      <% else %>
        <%= link_to 'FlashCard',import_path,class:"top_button mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
      <% end %>
    </div>
  </div>

  <div class="demo-card-wide mdl-card mdl-shadow--2dp top-mdl-card">
    <div class="mdl-card__title export_top"></div>
    <div class="mdl-card__supporting-text top-comment">
      自分でオリジナルのフラッシュカードを作ることができます
    </div>

    <div class="mdl-card__actions mdl-card--border">
      <%= link_to 'Export',new_card_file_path,class:"top_button mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    </div>
  </div>

  <div class="demo-card-wide mdl-card mdl-shadow--2dp top-mdl-card">
    <div class="mdl-card__title edit_top"></div>
    <div class="mdl-card__supporting-text top-comment">
      自分のフラッシュカードを編集・削除することができます
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <%= link_to 'Edit',card_files_path,class:"top_button mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    </div>
  </div>

  <div class="demo-card-wide mdl-card mdl-shadow--2dp top-mdl-card">
    <div class="mdl-card__title share_top"></div>
    <div class="mdl-card__supporting-text top-comment">
      フラッシュカードを公開したり<br>
      ダウンロードすることができます
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <%= link_to 'Share',"",:method => :post,class:"top_button mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    </div>
  </div>

  <div class="demo-card-wide mdl-card mdl-shadow--2dp top-mdl-card">
    <div class="mdl-card__title sign_up_top"></div>
    <div class="mdl-card__supporting-text top-comment">
      アカウントを作成します<br>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <%= link_to 'SignUp',new_user_registration_path,class:"top_button mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    </div>
  </div>

app/views/static_pages/import.html.erb
<div class="form">
  <label for="file" class="file">
    <input type="file" name="file" value="" id="file"></br>
    <div class="mdl-button mdl-js-button mdl-button--accent">
      ファイルを選択して決定をクリック
    </div>
  </label>
  <input type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect" onClick=loadJson() value=決定>
</div>